name: Build PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js if you're building a JavaScript/React project
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run build
        run: npm run build # Adjust this command to match your build script

      # Optionally, run tests if you have any
      #- name: Run tests
        #run: npm test # Adjust this command to match your test script
